spring.application.name=adoptions
#
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
#
spring.mvc.apiversion.default=1.1
spring.mvc.apiversion.use.header=x-dogs-version

#
management.tracing.sampling.probability=1.0

spring.threads.virtual.enabled=true

spring.modulith.events.jdbc.schema-initialization.enabled=true
spring.modulith.events.republish-outstanding-events-on-restart=true